import json
from pathlib import Path

classes = [
  ('artifice','Artífice','d8','Inteligência','full','Inteligência','Suporte','Conjuração baseada em Inteligência; ferramentas de ladrão e de artesão; infusões mágicas; foco em fabricar e imbuir objetos.', ['Alquimista','Armeiro','Artilheiro','Ferreiro de Batalha'], [('Infusões Mágicas',2),('Especialização de Artífice',3),('The Right Tool for the Job',3),('Melhoria no Valor de Habilidade',4),('Flash of Genius',7),('Magic Item Adept',10),('Spell-Storing Item',11),('Magic Item Savant',14),('Magic Item Master',18),('Soul of Artifice',20)]),
  ('barbaro','Bárbaro','d12','Força','none',None,'Linha de frente','Fúria, Defesa sem Armadura, armas marciais, resistência física e combate de linha de frente.', ['Caminho do Berserker','Caminho do Guerreiro Totêmico','Caminho do Battlerager','Caminho do Arauto da Tempestade','Caminho do Zelote','Caminho do Guardião Ancestral','Caminho da Besta','Caminho da Magia Selvagem','Caminho do Gigante'], [('Reckless Attack',2),('Danger Sense',2),('Melhoria no Valor de Habilidade',4),('Extra Attack',5),('Fast Movement',5),('Feral Instinct',7),('Brutal Critical',9),('Relentless Rage',11),('Persistent Rage',15),('Indomitable Might',18),('Primal Champion',20)]),
  ('bardo','Bardo','d8','Carisma','full','Carisma','Suporte','Conjuração baseada em Carisma; inspiração de bardo; perícias sociais e amplo repertório mágico.', ['Colégio do Conhecimento','Colégio do Valor','Colégio do Glamour','Colégio das Espadas','Colégio dos Sussurros','Colégio da Criação','Colégio da Eloquência','Colégio dos Espíritos'], [('Jack of All Trades',2),('Song of Rest',2),('Expertise',3),('Font of Inspiration',5),('Countercharm',6),('Magical Secrets',10),('Expertise',10),('Magical Secrets',14),('Magical Secrets',18),('Superior Inspiration',20)]),
  ('clerigo','Clérigo','d8','Sabedoria','full','Sabedoria','Suporte','Conjuração baseada em Sabedoria; domínio divino; armaduras e armas conforme a classe; magia divina preparada.', ['Domínio do Conhecimento','Domínio da Vida','Domínio da Luz','Domínio da Natureza','Domínio da Morte','Domínio da Tempestade','Domínio da Trapaça','Domínio da Guerra','Domínio Arcano','Domínio da Forja','Domínio do Túmulo','Domínio da Ordem','Domínio da Paz','Domínio do Crepúsculo'], [('Canalizar Divindade',2),('Expulsar Mortos-Vivos',2),('Melhoria no Valor de Habilidade',4),('Intervenção Divina',10),('Intervenção Divina aprimorada',20)]),
  ('druida','Druida','d8','Sabedoria','full','Sabedoria','Controle','Conjuração baseada em Sabedoria; linguagem druídica; vínculo com a natureza; Forma Selvagem.', ['Círculo da Terra','Círculo da Lua','Círculo dos Esporos','Círculo dos Sonhos','Círculo do Pastor','Círculo das Estrelas','Círculo do Fogo Selvagem'], [('Druídico',1),('Forma Selvagem',2),('Melhoria no Valor de Habilidade',4),('Corpo Atemporal',18),('Magias da Besta',18),('Arquídruida',20)]),
  ('guerreiro','Guerreiro','d10','Força ou Destreza','none',None,'Dano','Proficiência ampla em armas e armaduras; estilo de combate; alta resistência e foco em ataques.', ['Campeão','Mestre de Batalha','Cavaleiro Arcano','Cavaleiro Púrpura / Batedor de Estandarte','Arqueiro Arcano','Samurai','Cavaleiro','Cavaleiro Rúnico','Guerreiro Psiônico','Cavaleiro do Eco'], [('Segundo Fôlego',1),('Estilo de Combate',1),('Surto de Ação',2),('Arquétipo Marcial',3),('Extra Attack',5),('Indomável',9),('Extra Attack',11),('Extra Attack',20)]),
  ('monge','Monge','d8','Destreza e Sabedoria','none',None,'Dano','Artes marciais; Defesa sem Armadura; mobilidade e uso de ki; combate desarmado.', ['Caminho da Mão Aberta','Caminho das Sombras','Caminho dos Quatro Elementos','Caminho da Alma Solar','Caminho da Longa Morte','Caminho do Mestre Bêbado','Caminho do Kensei','Caminho da Misericórdia','Caminho do Eu Astral','Caminho do Dragão Ascendente'], [('Movimento sem Armadura',2),('Defletir Projéteis',3),('Queda Lenta',4),('Extra Attack',5),('Golpe Atordoante',5),('Ataques Mágicos',6),('Evasão',7),('Mente Tranquila',7),('Pureza do Corpo',10),('Língua do Sol e da Lua',13),('Alma Diamante',14),('Corpo Atemporal',15),('Corpo Vazio',18),('Eu Perfeito',20)]),
  ('paladino','Paladino','d10','Força e Carisma','half','Carisma','Linha de frente','Armaduras e armas marciais; magia baseada em Carisma; poder sagrado e proteção de aliados.', ['Juramento de Devoção','Juramento dos Ancestrais','Juramento de Vingança','Juramento da Coroa','Juramento de Conquista','Juramento de Redenção','Juramento da Glória','Juramento dos Vigilantes','Quebrador de Juramento'], [('Sentido Divino',1),('Imposição das Mãos',1),('Estilo de Combate',2),('Destruição Divina',2),('Juramento Sagrado',3),('Aura de Proteção',6),('Aura de Coragem',10),('Destruição Divina Aprimorada',11),('Limpeza de Doenças',14),('Melhoria de Auras',18)]),
  ('patrulheiro','Patrulheiro','d10','Destreza e Sabedoria','half','Sabedoria','Dano','Combate marcial; exploração; conjuração baseada em Sabedoria; sobrevivência e caça.', ['Caçador','Mestre das Feras','Perseguidor das Trevas','Andarilho do Horizonte','Caçador de Monstros','Guardião do Enxame','Andarilho Feérico','Guardião dos Dracos'], [('Inimigo Favorito',1),('Explorador Nato',1),('Estilo de Combate',2),('Conjuração',2),('Arquétipo',3),('Extra Attack',5),('Passo da Terra',8),('Esconder-se à Vista',10),('Desaparecer',14),('Sentidos Ferais',18),('Matador de Inimigos',20)]),
  ('ladino','Ladino','d8','Destreza','none',None,'Furtivo','Perícia e mobilidade; Expertise; Ataque Furtivo; ferramentas de infiltração.', ['Ladrão','Assassino','Trapaceiro Arcano','Inquisitivo','Mestre da Intriga','Espadachim','Explorador','Fantasma','Lâmina da Alma'], [('Expertise',1),('Ataque Furtivo',1),('Ação Ardilosa',2),('Arquétipo',3),('Uncanny Dodge',5),('Evasão',7),('Talento Confiável',11),('Blindsense',14),('Mente Escorregadia',15),('Elusivo',18),('Golpe de Sorte',20)]),
  ('feiticeiro','Feiticeiro','d6','Carisma','full','Carisma','Dano','Conjuração baseada em Carisma; magia inata; pontos de feitiçaria e Metamagia.', ['Linhagem Dracônica','Magia Selvagem','Alma Divina','Magia das Sombras','Feitiçaria da Tempestade','Mente Aberrante','Alma Mecânica','Feitiçaria Lunar'], [('Origem Mágica',1),('Fonte de Magia',2),('Metamagia',3),('Melhoria no Valor de Habilidade',4),('Metamagia adicional',10),('Metamagia adicional',17),('Restauração Feiticeira',20)]),
  ('bruxo','Bruxo','d8','Carisma','pact','Carisma','Dano','Magia baseada em Carisma; patrono extraplanar; espaços de magia recuperados em descanso curto; invocações.', ['Arquifada','O Grande Antigo','Infernal','O Imortal','Lâmina Maldita','Celestial','Abissal','Gênio','Morto-vivo'], [('Patrono',1),('Invocações Místicas',2),('Dádiva do Pacto',3),('Invocações adicionais',5),('Invocações adicionais',7),('Invocações adicionais',9),('Arcanum Místico',11),('Arcanum Místico',13),('Arcanum Místico',15),('Arcanum Místico',17),('Mestre do Eldritch',20)]),
  ('mago','Mago','d6','Inteligência','full','Inteligência','Controle','Conjuração baseada em Inteligência; grimório; preparação de magias; grande amplitude de escolas.', ['Escola de Abjuração','Escola de Conjuração','Escola de Adivinhação','Escola de Encantamento','Escola de Evocação','Escola de Ilusão','Escola de Necromancia','Escola de Transmutação','Cantor das Lâminas','Magia de Guerra','Magia da Cronurgia','Magia da Graviturgy','Ordem dos Escribas'], [('Recuperação Arcana',1),('Tradição Arcana',2),('Melhoria no Valor de Habilidade',4),('Domínio de Magias',18),('Magias de Assinatura',20)]),
]

def slug(value):
    import unicodedata, re
    return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFD',value).encode('ascii','ignore').decode().lower()).strip('-')

out=[]
for slug_value,name,die,ability,casting,casting_ability,role,description,subclasses,features in classes:
    out.append({
        'slug':slug_value,'name':name,'edition':'2014','status':'core','hitDie':die,'primaryAbility':ability,'role':role,'casting':casting,'castingAbility':casting_ability,
        'description':description,'resources':[],
        'subclasses':[{'slug':slug(s),'name':s,'edition':'2014','status':'core','source':'mapeamento_dnd5e_2014'} for s in subclasses],
        'features':[{'slug':slug(name)+'-'+slug(feature)+'-'+str(level),'name':feature,'level':level,'description':f'{feature} — marco funcional da classe {name}, conforme o mapeamento D&D 5e 2014.','source':'mapeamento_dnd5e_2014','edition':'2014'} for feature,level in features]
    })
Path('/home/ubuntu/new-rpg-manager/data/class-reference.json').write_text(json.dumps({'version':'2014.1','source':'mapeamento_dnd5e_2014','edition':'2014','classes':out},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'classes':len(out),'subclasses':sum(len(c['subclasses']) for c in out),'features':sum(len(c['features']) for c in out)},ensure_ascii=False))
